### ISSUE TITLE
libz3.dll could not be found on Windows

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [taw/z3#19]
Environment:
```
Windows 10
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
library: Z3 version 4.8.17 - 32 bit
gem: z3 (0.0.20220320)
```

z3 installed from: https://github.com/Z3Prover/z3/releases/download/z3-4.8.17/z3-4.8.17-x86-win.zip

z3 installation folder content (Windows):
```
z3-4.8.17-x86-win\bin:
  com.microsoft.z3.jar
  libz3.dll
  libz3.lib
  libz3.pdb
  libz3java.dll
  libz3java.lib
  Microsoft.Z3.deps.json
  Microsoft.Z3.dll
  Microsoft.Z3.pdb
  Microsoft.Z3.xml
  msvcp140.dll
  msvcp140_1.dll
  msvcp140_2.dll
  msvcp140_atomic_wait.dll
  msvcp140_codecvt_ids.dll
  vcomp140.dll
  vcruntime140.dll
  z3.exe
```

Example used from Getting Started: https://dev.to/taw/100-languages-speedrun-episode-23-ruby-z3-19b9

Issue log:
```
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.15.5-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': 
Could not open library 'libz3.so.4.8': The specified module could not be found.\r (LoadError)
.
Could not open library 'libz3.so.4.8.dll': The specified module could not be found.\r
.
Could not open library 'libz3.so': The specified module could not be found.\r
.
Could not open library 'libz3.so.dll': The specified module could not be found.\r
.
Could not open library 'z3': The specified module could not be found.\r
.
Could not open library 'z3.dll': The specified module could not be found.\r
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.15.5-x64-mingw32/lib/ffi/library.rb:99:in `map'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.15.5-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/z3-0.0.20220320/lib/z3/very_low_level.rb:7:in `<module:VeryLowLevel>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/z3-0.0.20220320/lib/z3/very_low_level.rb:5:in `<module:Z3>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/z3-0.0.20220320/lib/z3/very_low_level.rb:4:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/z3-0.0.20220320/lib/z3.rb:5:in `require_relative'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/z3-0.0.20220320/lib/z3.rb:5:in `<top (required)>'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from solve.rb:3:in `<main>'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- z3 (LoadError)
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

Potential root cause identified in 
c:\Ruby30-x64\lib\ruby\gems\3.0.0\gems\z3-0.0.20220320\lib\z3\very_low_level.rb
https://github.com/taw/z3/blob/master/lib/z3/very_low_level.rb#L7
`  ffi_lib ["libz3.so.4.8", "libz3.so", "z3"]`
  
 Issue could be solved by additional library name (compare with windows installation folder content above): 
`  ffi_lib ["libz3.so.4.8", "libz3.so", "z3", "libz3"]`

**Comment by taw** [comment]
Thanks. I have no good way of testing on Windows. I'll just add libz3 to the list there.

**Comment by taw** [comment]
Pushed updated version. Did it fix the issue?

**Comment by taw** [comment]
Hopefully this is resolved now. Feel free to reopen if not.
